name: Build & Deploy React to IIS
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Deploy to IIS folder
        run: |
          Remove-Item E:\test_iis\PMDVeg\* -Recurse -Force
          Copy-Item .\build\* E:\test_iis\PMDVeg\ -Recurse -Force
        shell: pwsh
