name: React CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # 添加这一行，允许在页面手动点击运行

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build